import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Box, CircleCheck, Code2, Play, RotateCw, Square, Terminal, Trash2 } from 'lucide-react';
import { api } from '../../api';
import type { MetricsRange, MetricsSnapshot, PHPVersion, ProjectInfo, SystemStatus } from '../../types';

function ServiceCard({ name, up, detail }: { name: string; up: boolean; detail: string }) { return <article className="service-card"><div><Box size={17}/><strong>{name}</strong></div><span className={up ? 'service-ok' : 'service-down'}>{up ? <CircleCheck size={14}/> : <AlertTriangle size={14}/>} {up ? 'Disponível' : 'Indisponível'}</span><small>{detail}</small></article>; }

export function Overview({ project, system, busy, phpVersions, onPHPVersion, onRemove, onAction }: { project: ProjectInfo; system: SystemStatus | null; busy?: string; phpVersions: PHPVersion[]; onPHPVersion: (version: string) => void; onRemove: () => void; onAction: (action: 'start'|'stop'|'restart'|'build'|'deps'|'doctor') => void }) {
  const [range, setRange] = useState<MetricsRange>('1h');
  const [metrics, setMetrics] = useState<MetricsSnapshot | null>(null);
  const [metricsLoading, setMetricsLoading] = useState(false);
  const [metricsRefresh, setMetricsRefresh] = useState(0);
  const canRunDev = project.effectiveMode === 'dev' || project.framework === 'laravel';
  const installedPHP = phpVersions.filter(version => version.installed);
  useEffect(() => { let current = true; setMetricsLoading(true); void api.getMetrics(project.name, range).then(value => { if (current) setMetrics(value); }).catch(() => { if (current) setMetrics(null); }).finally(() => { if (current) setMetricsLoading(false); }); return () => { current = false; }; }, [project.name, range, metricsRefresh]);
  return <div className="overview-content"><section><label className="section-label">RUNTIME E WORKERS</label><div className="runtime-toolbar">{project.effectiveMode === 'php' ? <label className="runtime-select"><Code2 size={16}/><span>PHP</span><select aria-label="Versão do PHP" value={project.phpVersion || ''} onChange={e => onPHPVersion(e.target.value)} disabled={!!busy || installedPHP.length === 0}><option value="">{installedPHP.length ? 'Selecionar versão' : 'Nenhuma instalada'}</option>{installedPHP.map(version => <option key={version.version} value={version.version}>{version.version}{version.configured ? ' (padrão)' : ''}</option>)}</select></label> : <div><Code2 size={16}/><span>{project.effectiveMode}</span></div>}{canRunDev && <div><Terminal size={16}/><span>{project.packageManager || 'npm'} {project.devPort ? `:${project.devPort}` : ''}</span></div>}<span className={`process-pill ${project.status}`}><i/> {canRunDev ? (project.devRunning ? 'HMR local ativo' : 'HMR local parado') : 'Em execução'}</span><div className="quick-actions">{canRunDev && (project.devRunning ? <button disabled={!!busy} onClick={() => onAction('stop')}><Square size={14}/> Parar HMR local</button> : <button disabled={!!busy} onClick={() => onAction('start')}><Play size={14}/> Iniciar HMR local</button>)}{canRunDev && <button disabled={!!busy} onClick={() => onAction('restart')}><RotateCw size={14}/> Reiniciar HMR</button>}<button disabled={!!busy} onClick={() => onAction('build')}>Atualizar preview LAN</button><button disabled={!!busy} onClick={() => onAction('deps')}>Instalar dependências</button><button className="danger-action" disabled={!!busy} onClick={onRemove}><Trash2 size={14}/> Remover</button></div></div></section><section><label className="section-label">SERVIÇOS</label><div className="services-grid"><ServiceCard name="Caddy Windows" up={!!system?.windowsCaddyRunning} detail="Borda e TLS local"/><ServiceCard name="Caddy WSL" up={!!system?.wslCaddyRunning} detail="Proxy e aplicações Linux"/>{project.effectiveMode === 'php' && <ServiceCard name="PHP-FPM" up={project.status === 'ready'} detail={`PHP ${project.phpVersion || 'padrão'}`}/>} {canRunDev && <ServiceCard name="HMR local" up={project.devRunning} detail="Vite em .localhost"/>}<ServiceCard name="Preview LAN" up={project.lanPreviewState === 'ready'} detail={project.lanPreviewState === 'paused' ? 'Pausado durante HMR local' : 'Manifest compilado'}/></div></section>{project.lanPreviewState === 'paused' && <p className="endpoint-notice">O preview LAN está pausado enquanto o HMR local está ativo. Use “Atualizar preview LAN” para parar o dev, gerar o build e publicar uma versão estável na rede.</p>}<MetricsSection metrics={metrics} range={range} onRange={setRange} loading={metricsLoading} onRefresh={() => setMetricsRefresh(value => value + 1)}/></div>;
}

function MetricsSection({ metrics, range, onRange, loading, onRefresh }: { metrics: MetricsSnapshot | null; range: MetricsRange; onRange: (range: MetricsRange) => void; loading: boolean; onRefresh: () => void }) {
  const buckets = metrics?.latencyBuckets ?? [25, 50, 100, 250, 500, 1000, null].map(upperBoundMs => ({ upperBoundMs, count: 0 }));
  const routes = metrics?.routes ?? [];
  return <section className="metrics-section"><div className="metrics-heading"><label className="section-label">TEMPO DE REQUISIÇÃO</label><div className="metrics-controls"><button className="metrics-refresh" disabled={loading} onClick={onRefresh}><RotateCw size={13}/> {loading ? 'Atualizando…' : 'Atualizar'}</button><div className="range-tabs">{(['15m','1h','24h','7d'] as MetricsRange[]).map(item => <button key={item} className={range === item ? 'active' : ''} onClick={() => onRange(item)}>{item}</button>)}</div></div></div>{!metrics && <p className="metrics-no-data">Nenhuma requisição registrada nos últimos {range}. Os gráficos permanecem prontos para novas amostras.</p>}<div className="metrics-grid"><MetricCard label="TÍPICO" value={formatLatency(metrics?.p50Ms)} unit="ms" caption="mediana"/><MetricCard label="P95" value={formatLatency(metrics?.p95Ms)} unit="ms" caption="cauda"/><MetricCard label="REQUISIÇÕES" value={(metrics?.requests ?? 0).toLocaleString('pt-BR')} caption={`nos últimos ${range}`}/><MetricCard label="TAXA DE ERROS" value={formatPercent(metrics?.errorRate ?? 0)} unit="%" caption={`${metrics?.errorCount ?? 0} de ${(metrics?.requests ?? 0).toLocaleString('pt-BR')} foram 4xx/5xx`} warning={(metrics?.errorRate ?? 0) > 1}/></div>{(metrics?.excludedColdStarts ?? 0) > 0 && <p className="metrics-note">✣ {metrics!.excludedColdStarts} inícios a frio excluídos do tempo</p>}<div className="charts-grid"><LatencyHistogram buckets={buckets}/><TrafficChart points={metrics?.traffic ?? []}/></div><SlowRoutes routes={routes}/><RoutesTable routes={routes}/></section>;
}
function formatLatency(value: number | null | undefined): string | null { return value == null ? null : value.toLocaleString('pt-BR', { maximumFractionDigits: 1 }); }
function formatPercent(value: number): string { return value.toLocaleString('pt-BR', { maximumFractionDigits: 1 }); }
function MetricCard({ label, value, unit, caption, warning }: { label: string; value: number|string|null; unit?: string; caption: string; warning?: boolean }) { return <article className="metric-card"><label>{label}</label><strong className={warning ? 'warning-value' : ''}>{value === null ? 'Sem dados' : value}{value !== null && unit && <small>{unit}</small>}</strong><span>{caption}</span></article>; }
function LatencyHistogram({ buckets }: { buckets: MetricsSnapshot['latencyBuckets'] }) { const total = buckets.reduce((sum, item) => sum + item.count, 0); const max = Math.max(...buckets.map(item => item.count), 1); const labels = ['<25ms','<50ms','<100ms','<250ms','<500ms','<1s','>1s']; return <article className="chart-card"><div className="chart-title"><label>TEMPO DE RESPOSTA</label></div>{total ? <div className="histogram">{buckets.map((item, i) => <div className={`hist-bar bar-${i}`} key={item.upperBoundMs ?? 'over'}><i style={{ height: `${Math.max(3, item.count / max * 100)}%` }}/><small>{labels[i]}</small></div>)}</div> : <div className="chart-empty">Sem respostas no período</div>}</article>; }
function TrafficChart({ points }: { points: MetricsSnapshot['traffic'] }) { const max = Math.max(...points.map(point => point.requestsPerMinute), 1); const path = points.map((point, i) => `${i ? 'L' : 'M'} ${(i / Math.max(points.length - 1, 1)) * 100} ${100 - point.requestsPerMinute / max * 80}`).join(' '); const area = path ? `${path} L 100 100 L 0 100 Z` : ''; return <article className="chart-card"><div className="chart-title"><label>TAXA DE TRANSFERÊNCIA</label><span>req/min</span></div>{points.length ? <><svg className="traffic-chart" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Requisições por minuto"><path className="traffic-area" d={area}/><path className="traffic-line" d={path}/></svg><div className="chart-axis"><span>{points[0]?.at || '—'}</span><span>{points[points.length - 1]?.at || '—'}</span></div></> : <div className="chart-empty">Sem tráfego no período</div>}</article>; }
function SlowRoutes({ routes }: { routes: MetricsSnapshot['routes'] }) { const rows = routes.slice().sort((a,b) => (b.p95Ms || 0) - (a.p95Ms || 0)).slice(0, 5); const max = Math.max(...rows.map(r => r.p95Ms || 0), 1); return <article className="slow-routes"><label className="section-label">ROTAS MAIS LENTAS</label>{rows.length ? rows.map(route => <div className="slow-route" key={`${route.method}-${route.normalizedPath}`}><span className={`method method-${route.method.toLowerCase()}`}>{route.method}</span><code>{route.normalizedPath}</code><div className="latency-bar"><i style={{ width: `${(route.p95Ms || 0) / max * 100}%` }}/></div><strong>{route.p95Ms === null ? 'Sem dados' : `${formatLatency(route.p95Ms)} ms`}</strong></div>) : <div className="table-empty">Nenhuma rota registrada neste período.</div>}</article>; }
function RoutesTable({ routes }: { routes: MetricsSnapshot['routes'] }) { const [tab, setTab] = useState<'routes'|'recent'>('routes'); const sorted = useMemo(() => routes.slice().sort((a,b) => (b.p95Ms || 0) - (a.p95Ms || 0)), [routes]); return <article className="routes-table"><div className="table-tabs"><button className={tab === 'routes' ? 'active' : ''} onClick={() => setTab('routes')}>Rotas</button><button className={tab === 'recent' ? 'active' : ''} onClick={() => setTab('recent')}>Requisições recentes</button></div>{tab === 'recent' ? <div className="table-empty">Registros recentes não estão disponíveis sem expor dados sensíveis.</div> : <><div className="table-head"><span>ROTA</span><span>P50</span><span>P95</span><span>LATÊNCIA</span><span>REQUISIÇÕES</span></div>{sorted.length ? sorted.map(route => <div className="table-row" key={`${route.method}-${route.normalizedPath}`}><span><b className={`method method-${route.method.toLowerCase()}`}>{route.method}</b><code>{route.normalizedPath}</code></span><span>{route.p50Ms === null ? '—' : `${formatLatency(route.p50Ms)} ms`}</span><strong className={(route.p95Ms || 0) > 300 ? 'danger-text' : (route.p95Ms || 0) > 150 ? 'warning-text' : ''}>{route.p95Ms === null ? '—' : `${formatLatency(route.p95Ms)} ms`}</strong><span className="mini-latency"><i style={{ width: `${Math.min(100, (route.p95Ms || 0) / 5)}%` }}/></span><span>{route.requests.toLocaleString('pt-BR')}</span></div>) : <div className="table-empty table-empty-grid">Nenhuma rota registrada neste período.</div>}</>}</article>; }
