package php

import (
	"fmt"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/dougkusanagi/dev-lan/internal/domain"
	"github.com/dougkusanagi/dev-lan/internal/platform"
)

type PoolPlan struct {
	Version   string
	Name      string
	Socket    string
	FPMBinary string
	FileName  string
	Contents  string
}

type versionPlan struct {
	Version   string
	FPMBinary string
	FileName  string
	Pools     []PoolPlan
}

var safeNamePattern = regexp.MustCompile(`^[a-z][a-z0-9-]{0,62}$`)

func poolFileName(version string) string {
	return "php-" + strings.ReplaceAll(version, ".", "-") + ".conf"
}

func poolName(version, name string) string {
	if name == "shared" {
		name = "isolated_shared"
	}
	return "devlan_" + strings.ReplaceAll(version, ".", "_") + "_" + strings.ReplaceAll(name, "-", "_")
}

func fpmBinary(version string) string { return "php-fpm" + version }

// Plans creates one PHP-FPM master configuration per installed/configured
// branch. A shared pool always exists; projects opt into an isolated pool by
// setting php_isolated_pool=true.
func Plans(cfg domain.Config) ([]PoolPlan, error) {
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	versions := append([]domain.PHPVersionConfig(nil), cfg.PHPVersions...)
	sort.Slice(versions, func(i, j int) bool { return versions[i].Version < versions[j].Version })
	plans := make([]PoolPlan, 0, len(versions))
	for _, version := range versions {
		versionPlan := versionPlan{Version: version.Version, FPMBinary: version.FPMBinary, FileName: poolFileName(version.Version)}
		if versionPlan.FPMBinary == "" {
			versionPlan.FPMBinary = fpmBinary(version.Version)
		}
		shared := PoolPlan{
			Version:   version.Version,
			Name:      "shared",
			Socket:    sharedSocket(cfg, version),
			FPMBinary: versionPlan.FPMBinary,
			FileName:  versionPlan.FileName,
		}
		versionPlan.Pools = append(versionPlan.Pools, shared)
		for _, project := range cfg.Projects {
			if cfg.EffectivePHPVersion(project) != version.Version || !cfg.PHPIsolated(project) {
				continue
			}
			if !safeNamePattern.MatchString(project.Name) {
				return nil, fmt.Errorf("nome de projeto inválido para pool PHP: %q", project.Name)
			}
			versionPlan.Pools = append(versionPlan.Pools, PoolPlan{
				Version:   version.Version,
				Name:      project.Name,
				Socket:    domain.PHPIsolatedSocket(version.Version, project.Name),
				FPMBinary: versionPlan.FPMBinary,
				FileName:  versionPlan.FileName,
			})
		}
		contents, err := renderMasterConfig(cfg, version, versionPlan.Pools)
		if err != nil {
			return nil, err
		}
		for i := range versionPlan.Pools {
			versionPlan.Pools[i].Contents = contents
		}
		plans = append(plans, versionPlan.Pools...)
	}
	return plans, nil
}

func sharedSocket(cfg domain.Config, version domain.PHPVersionConfig) string {
	if version.Socket != "" {
		return version.Socket
	}
	return domain.PHPSharedSocket(version.Version)
}

func renderMasterConfig(cfg domain.Config, version domain.PHPVersionConfig, pools []PoolPlan) (string, error) {
	var b strings.Builder
	b.WriteString("; Code generated by DevLAN. DO NOT EDIT.\n")
	b.WriteString("[global]\n")
	b.WriteString("daemonize = yes\n")
	fmt.Fprintf(&b, "pid = /run/devlan/php/%s/php-fpm.pid\n", version.Version)
	fmt.Fprintf(&b, "error_log = /var/log/devlan/php-%s-fpm.log\n\n", version.Version)
	for _, pool := range pools {
		poolConfig := cfg.PHPFPMPool
		if configured, found := cfg.PHPVersion(version.Version); found && !configured.Pool.IsZero() {
			poolConfig = mergePool(poolConfig, configured.Pool)
		}
		for _, project := range cfg.Projects {
			if pool.Name == project.Name && cfg.EffectivePHPVersion(project) == version.Version && project.PHPFPMPool != nil {
				poolConfig = *project.PHPFPMPool
			}
		}
		if err := poolConfig.Normalize(); err != nil {
			return "", err
		}
		section := poolName(version.Version, pool.Name)
		fmt.Fprintf(&b, "[%s]\n", section)
		b.WriteString("user = www-data\n")
		b.WriteString("group = www-data\n")
		fmt.Fprintf(&b, "listen = %s\n", pool.Socket)
		b.WriteString("listen.owner = caddy\n")
		b.WriteString("listen.group = www-data\n")
		b.WriteString("listen.mode = 0660\n")
		b.WriteString("clear_env = yes\n")
		b.WriteString("catch_workers_output = yes\n")
		b.WriteString("pm = ondemand\n")
		fmt.Fprintf(&b, "pm.max_children = %d\n", poolConfig.MaxChildren)
		fmt.Fprintf(&b, "pm.process_idle_timeout = %s\n", poolConfig.IdleTimeout)
		fmt.Fprintf(&b, "pm.max_requests = %d\n", poolConfig.MaxRequests)
		fmt.Fprintf(&b, "access.log = /var/log/devlan/php-%s-%s-access.log\n\n", version.Version, pool.Name)
	}
	return b.String(), nil
}

func mergePool(base, override domain.PHPFPMPoolConfig) domain.PHPFPMPoolConfig {
	if override.MaxChildren != 0 {
		base.MaxChildren = override.MaxChildren
	}
	if override.IdleTimeout != "" {
		base.IdleTimeout = override.IdleTimeout
	}
	if override.MaxRequests != 0 {
		base.MaxRequests = override.MaxRequests
	}
	return base
}

func PlansByFile(cfg domain.Config) (map[string]string, []platform.PHPPoolSpec, error) {
	plans, err := Plans(cfg)
	if err != nil {
		return nil, nil, err
	}
	files := make(map[string]string)
	runtimePlans := make([]platform.PHPPoolSpec, 0, len(cfg.PHPVersions))
	seenFiles := map[string]struct{}{}
	for _, plan := range plans {
		if _, exists := seenFiles[plan.FileName]; !exists {
			files[plan.FileName] = plan.Contents
			seenFiles[plan.FileName] = struct{}{}
			runtimePlans = append(runtimePlans, platform.PHPPoolSpec{Version: plan.Version, Name: plan.Name, FPMBinary: plan.FPMBinary})
		}
	}
	return files, runtimePlans, nil
}

func SocketFor(cfg domain.Config, project domain.Project) string {
	return cfg.PHPSocket(project)
}

func DisplayPath(root, version string) string {
	return filepath.Join(root, poolFileName(version))
}

func PoolSummary(cfg domain.Config, project domain.Project) string {
	if cfg.PHPIsolated(project) {
		return "isolated"
	}
	return "shared"
}
