package caddy

import (
	"fmt"
	pathpkg "path"
	"strconv"
	"strings"

	"github.com/dougkusanagi/dev-lan/internal/domain"
)

const generatedHeader = "# Code generated by DevLAN. DO NOT EDIT.\n"

type Route struct {
	Project domain.Project
	Mode    domain.Mode
}

func Routes(cfg domain.Config) ([]Route, error) {
	resolved, err := cfg.ResolvedProjects()
	if err != nil {
		return nil, err
	}
	routes := make([]Route, 0, len(resolved))
	for _, item := range resolved {
		if item.Mode != domain.ModePHP {
			return nil, fmt.Errorf("projeto %q resolve para modo %q: %w", item.Project.Name, item.Mode, domain.ErrUnsupportedMode)
		}
		routes = append(routes, Route{Project: item.Project, Mode: item.Mode})
	}
	return routes, nil
}

// RenderWindows creates the stable LAN edge. It intentionally contains no
// project-specific values, so most project changes only affect the WSL file.
func RenderWindows(cfg domain.Config) (string, error) {
	if err := cfg.Validate(); err != nil {
		return "", err
	}
	port := fmt.Sprintf(":%d", cfg.WindowsPort)
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("{\n")
	b.WriteString("    auto_https off\n")
	b.WriteString("    admin off\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "%s {\n", port)
	b.WriteString("    bind 0.0.0.0\n")
	b.WriteString("    encode gzip\n")
	fmt.Fprintf(&b, "    reverse_proxy 127.0.0.1:%d\n", cfg.WSLPort)
	b.WriteString("}\n")
	return b.String(), nil
}

// RenderWSL generates one deterministic route per explicitly registered
// Laravel project. The exact and wildcard paths are both matched so /name and
// /name/... behave consistently.
func RenderWSL(cfg domain.Config) (string, error) {
	routes, err := Routes(cfg)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("{\n")
	b.WriteString("    auto_https off\n")
	b.WriteString("    admin off\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, ":%d {\n", cfg.WSLPort)
	b.WriteString("    encode gzip\n")
	b.WriteString("    @devlan_health path /__devlan/health\n")
	b.WriteString("    respond @devlan_health \"ok\" 200\n\n")

	for _, route := range routes {
		name := route.Project.Name
		publicRoot := pathpkg.Join(route.Project.Path, "public")
		fmt.Fprintf(&b, "    @%s path /%s /%s/*\n", name, name, name)
		fmt.Fprintf(&b, "    handle @%s {\n", name)
		fmt.Fprintf(&b, "        uri strip_prefix /%s\n", name)
		fmt.Fprintf(&b, "        request_header X-Forwarded-Prefix /%s\n", name)
		fmt.Fprintf(&b, "        root * %s\n", quoteCaddy(publicRoot))
		fmt.Fprintf(&b, "        php_fastcgi unix/%s\n", cfg.PHPFPMOsocket)
		b.WriteString("        file_server\n")
		b.WriteString("    }\n\n")
	}

	b.WriteString("    respond \"not found\" 404\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func quoteCaddy(value string) string {
	// Caddyfile quoted strings use the same common escapes as JSON strings for
	// the path characters that can reach this generator.
	return strconv.Quote(value)
}
